title = "Started a fellowship at Goodfire"
date = "2026-01-01"
description = "I joined Goodfire! So excited to build tools for scientific discovery."
icon = "fa-solid fa-fire"
link = "https://www.goodfire.ai/"
