title = "Covariance-based sequence pooling"
date = "2026-04-10"
description = ""
link = "https://www.goodfire.ai/research/covariance-pooling#"
image = "@/assets/thumbnails/covariance.jpeg"
external = true
