title = "Bilinear autoencoders find interpretable manifolds"
shortTitle = "Bilinear Autoencoders"
date = "2026-05-28"
conference = "NeurIPS'25"
labels = ["workshop", "spotlight"]
description = "An autoencoder architecture that decomposes activations into polynomial manifolds."
link = "/research/bae"
authors = ["Thomas Dooms*", "Ward Gauderis*", "Geraint A. Wiggins", "Jose Oramas"]

paper = "https://arxiv.org/abs/2605.08891"
code = "https://github.com/tdooms/bae"
demo = "/bae"
models = "https://huggingface.co/tdooms/qwen3-0.6b-base-scope"

bibtex = """
@misc{dooms2026bilinearautoencoders,
      title={Bilinear autoencoders find interpretable manifolds},
      author={Thomas Dooms and Ward Gauderis and Geraint A. Wiggins and Jose Oramas},
      year={2026},
      eprint={2605.08891},
      archivePrefix={arXiv},
      primaryClass={cs.LG},
      url={https://arxiv.org/abs/2605.08891},
}
"""
